import type { Curso, Usuario } from './types';

/** Contenido de respaldo para que la landing luzca completa antes de conectar Supabase. */
export const PROFESORES_DEMO: Usuario[] = [
  {
    id: 'demo-prof-1',
    usuario: 'jmendoza',
    email: 'j.mendoza@petrolearn.com.ve',
    nombre: 'Ing. Jose Mendoza',
    rol: 'profesor',
    especialidad: 'Perforacion y Completacion de Pozos',
    bio: 'Veinte anos en operaciones upstream en la Faja Petrolifera del Orinoco.',
    avatar_url: null,
    telefono: null,
    activo: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-prof-2',
    usuario: 'lrivas',
    email: 'l.rivas@petrolearn.com.ve',
    nombre: 'Ing. Luisa Rivas',
    rol: 'profesor',
    especialidad: 'Refinacion y Procesos Downstream',
    bio: 'Especialista en unidades de destilacion atmosferica y craqueo catalitico.',
    avatar_url: null,
    telefono: null,
    activo: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-prof-3',
    usuario: 'cbastidas',
    email: 'c.bastidas@petrolearn.com.ve',
    nombre: 'Lic. Carlos Bastidas',
    rol: 'profesor',
    especialidad: 'Seguridad Industrial y Ambiente',
    bio: 'Auditor SIAHO certificado, formador en normativa COVENIN y API.',
    avatar_url: null,
    telefono: null,
    activo: true,
    creado_en: new Date().toISOString(),
  },
];

export const CURSOS_DEMO: Curso[] = [
  {
    id: 'demo-curso-1',
    titulo: 'Fundamentos de Perforacion de Pozos',
    slug: 'fundamentos-perforacion',
    descripcion: 'Desde la geologia del yacimiento hasta el diseno del programa de perforacion rotatoria.',
    categoria: 'Upstream',
    nivel: 'Basico',
    duracion_horas: 24,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-curso-2',
    titulo: 'Operacion de Unidades de Destilacion',
    slug: 'unidades-destilacion',
    descripcion: 'Balance de materia y energia, control de torres y optimizacion de cortes.',
    categoria: 'Refinacion',
    nivel: 'Avanzado',
    duracion_horas: 40,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-curso-3',
    titulo: 'Seguridad en Instalaciones de Hidrocarburos',
    slug: 'seguridad-hidrocarburos',
    descripcion: 'Analisis de riesgos, permisos de trabajo y respuesta ante emergencias.',
    categoria: 'Seguridad Industrial',
    nivel: 'Intermedio',
    duracion_horas: 18,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-curso-4',
    titulo: 'Transporte y Almacenamiento de Crudo',
    slug: 'transporte-almacenamiento',
    descripcion: 'Oleoductos, patios de tanques, cisternas y control de perdidas.',
    categoria: 'Midstream',
    nivel: 'Intermedio',
    duracion_horas: 22,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-curso-5',
    titulo: 'Comercializacion de Productos Derivados',
    slug: 'comercializacion-derivados',
    descripcion: 'Cadena downstream, formacion de precios y logistica de distribucion.',
    categoria: 'Downstream',
    nivel: 'Basico',
    duracion_horas: 16,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
  {
    id: 'demo-curso-6',
    titulo: 'Normativa y Gerencia de Proyectos Petroleros',
    slug: 'gerencia-proyectos',
    descripcion: 'Marco legal venezolano, contratacion y control de proyectos de capital.',
    categoria: 'Gerencia y Normativa',
    nivel: 'Avanzado',
    duracion_horas: 30,
    portada_url: null,
    publicado: true,
    creado_en: new Date().toISOString(),
  },
];
